const itemLists = {
    shipment: [
        { name: "Acorn", image: "images/Acorn.png", link: "https://www.deviantart.com/nemeionadmin/art/Acorn-893639185", weight: 20 },
        { name: "Alcohol", image: "images/Alcohol.png", link: "https://www.deviantart.com/nemeionadmin/art/Alcohol-937794821", weight: 29 },
        { name: "Amber", image: "images/Amber.png", link: "https://www.deviantart.com/nemeionadmin/art/Amber-893639260", weight: 13 },
        { name: "Ancient Tablet", image: "images/AncientTablet.png", link: "https://www.deviantart.com/nemeionadmin/art/Ancient-Tablet-1048407956", weight: 3 },
        { name: "Ancient Time Scroll", image: "images/AncientTimeScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Ancient-Time-Scroll-1154720381", weight: 2 },
        { name: "Anthea's Vase", image: "images/AntheaVase.png", link: "https://www.deviantart.com/nemeionadmin/art/Anthea-s-Vase-1048408927", weight: 14 },
        { name: "Anvil", image: "images/Anvil.png", link: "https://www.deviantart.com/nemeionadmin/art/Anvil-893639615", weight: 13 },
        { name: "Aphrodite's Lament", image: "images/AphroLament.png", link: "https://www.deviantart.com/nemeionadmin/art/Aphrodite-s-Lament-1048409662", weight: 3 },
        { name: "Aphrodite's Passion", image: "images/AphroPassion.png", link: "https://www.deviantart.com/nemeionadmin/art/Aphrodite-s-Passion-893639756", weight: 4 },
        { name: "Apollo's Feather", image: "images/ApolloFeather.png", link: "https://www.deviantart.com/nemeionadmin/art/Apollo-s-Feather-990294160", weight: 2 },
        { name: "Arrows", image: "images/Arrows.png", link: "https://www.deviantart.com/nemeionadmin/art/Arrows-862972674", weight: 7 },
        { name: "Axe", image: "images/Axe.png", link: "https://www.deviantart.com/nemeionadmin/art/Axe-893639834", weight: 7 },
        { name: "Bandages", image: "images/Bandages.png", link: "https://www.deviantart.com/nemeionadmin/art/Bandages-893640088", weight: 12 },
        { name: "Bear Brown", image: "images/BearBrown.png", link: "https://www.deviantart.com/nemeionadmin/art/Bear-Brown-893640141", weight: 1 },
        { name: "Befuddling Brew", image: "images/BefuddlingBrew.png", link: "https://www.deviantart.com/nemeionadmin/art/Befuddling-Brew-1156343809", weight: 1 },
        { name: "Black Currants", image: "images/BlackCurrants.png", link: "https://www.deviantart.com/nemeionadmin/art/Black-Currants-862973108", weight: 9 },
        { name: "Blessing of Hera", image: "images/HeraBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Hera-1000420405", weight: 1 },
        { name: "Blessing of Poseidon", image: "images/PoseidonBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Poseidon-990292572", weight: 1 },
        { name: "Blessing of Volcan", image: "images/VolcanBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Volcan-990292998", weight: 1 },
        { name: "Blessing of Zeus", image: "images/ZeusBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Zeus-1000420032", weight: 1 },
        { name: "Blistering Bile", image: "images/BlisteringBile.png", link: "https://www.deviantart.com/nemeionadmin/art/Blistering-Bile-1137290581", weight: 1 },
        { name: "Bloodstone", image: "images/Bloodstone.png", link: "https://www.deviantart.com/nemeionadmin/art/Bloodstone-893640348", weight: 3 },
        { name: "Blossom of Chloris", image: "images/Chloris.png", link: "https://www.deviantart.com/nemeionadmin/art/Blossom-of-Chloris-668240785", weight: 5 },
        { name: "Blue Crystal", image: "images/BlueCrystal.png", link: "https://www.deviantart.com/nemeionadmin/art/Blue-Crystal-893640417", weight: 6 },
        { name: "Blue Geode", image: "images/BlueGeode.png", link: "https://www.deviantart.com/nemeionadmin/art/Blue-Geode-893799887", weight: 6 },
        { name: "Boar Black", image: "images/BoarBlack.png", link: "https://www.deviantart.com/nemeionadmin/art/Boar-Black-893640617", weight: 1 },
        { name: "Bolts", image: "images/Bolts.png", link: "https://www.deviantart.com/nemeionadmin/art/Bolts-1149001552", weight: 9 },
        { name: "Bottled Lightning", image: "images/BottledLightning.png", link: "https://www.deviantart.com/nemeionadmin/art/Bottled-Lightning-990293347", weight: 1 },
        { name: "Bountiful Tonic", image: "images/BountifulTonic.png", link: "https://www.deviantart.com/nemeionadmin/art/Bountiful-Tonic-1048415748", weight: 3 },
        { name: "Bow", image: "images/Bow.png", link: "https://www.deviantart.com/nemeionadmin/art/Bow-893640484", weight: 6 },
        { name: "Bread", image: "images/Bread.png", link: "https://www.deviantart.com/nemeionadmin/art/Bread-893640850", weight: 9 },
        { name: "Brush", image: "images/Brush.png", link: "https://www.deviantart.com/nemeionadmin/art/Brush-893640969", weight: 7 },
        { name: "Brute Potion", image: "images/BrutePotion.png", link: "https://www.deviantart.com/nemeionadmin/art/Brute-Potion-893641009", weight: 3 },
        { name: "Chalice", image: "images/Chalice.png", link: "https://www.deviantart.com/nemeionadmin/art/Chalice-893641224", weight: 15 },
        { name: "Champion's Blade", image: "images/ChampionBlade.png", link: "https://www.deviantart.com/nemeionadmin/art/Champion-s-Blade-795623439", weight: 7 },
        { name: "Cerberus Pale", image: "images/CerberusPale.png", link: "https://www.deviantart.com/nemeionadmin/art/Cerberus-Pale-1048405297", weight: 1 },
        { name: "Chimera Tan", image: "images/ChimeraTan.png", link: "https://www.deviantart.com/nemeionadmin/art/Chimera-Tan-1048405029", weight: 1 },
        { name: "Chroma Ingot", image: "images/ChromaIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Chroma-Ingot-990297997", weight: 2 },
        { name: "Chunk of Azurite", image: "images/AzuriteChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Azurite-990298338", weight: 2 },
        { name: "Chunk of Copper", image: "images/CopperChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Copper-893641267", weight: 5 },
        { name: "Chunk of Gold", image: "images/GoldChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Gold-893641299", weight: 4 },
        { name: "Chunk of Iron", image: "images/IronChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Iron-893641343", weight: 3 },
        { name: "Chunk of Silver", image: "images/SilverChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Silver-893641392", weight: 2 },
        { name: "Chunk of Unakite", image: "images/UnakiteChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Unakite-990298579", weight: 2 },
        { name: "Clan Creation Deed", image: "images/ClanDeed.png", link: "https://www.deviantart.com/nemeionadmin/art/Clan-Creation-Deed-869944958", weight: 7 },
        { name: "Cluster of Gems", image: "images/GemCluster.png", link: "https://www.deviantart.com/nemeionadmin/art/Cluster-of-Gems-990299363", weight: 2 },
        { name: "Coffee Beans", image: "images/CoffeeBeans.png", link: "https://www.deviantart.com/nemeionadmin/art/Coffee-Beans-1149001000", weight: 17 },
        { name: "Common Scroll", image: "images/CScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Common-Scroll-893641746", weight: 2 },
        { name: "Copper Ingot", image: "images/CopperIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Copper-Ingot-893641788", weight: 2 },
        { name: "Cougar Tan", image: "images/CougarTan.png", link: "https://www.deviantart.com/nemeionadmin/art/Cougar-Tan-893641980", weight: 1 },
        { name: "Creature Crate", image: "images/CreatureCrate.png", link: "https://www.deviantart.com/nemeionadmin/art/Creature-Crate-893641939", weight: 5 },
        { name: "Crocodile Green", image: "images/CrocGreenn.png", link: "https://www.deviantart.com/nemeionadmin/art/Crocodile-Green-893642312", weight: 1 },
        { name: "Crow Hooded", image: "images/CrowHooded.png", link: "https://www.deviantart.com/nemeionadmin/art/Crow-Hooded-1106821637", weight: 1 },
        { name: "Crow Albino", image: "images/CrowAlbino.png", link: "https://www.deviantart.com/nemeionadmin/art/Crow-Albino-893642163", weight: 1 },
        { name: "Crow Vitiligo", image: "images/CrowVitiligo.png", link: "https://www.deviantart.com/nemeionadmin/art/Crow-Vitiligo-893642124", weight: 1 },
        { name: "Crow Black", image: "images/CrowBlack.png", link: "https://www.deviantart.com/nemeionadmin/art/Crow-Black-893642077", weight: 1 },
        { name: "Decoration Coffer", image: "images/DecorCoffer.png", link: "https://www.deviantart.com/nemeionadmin/art/Decoration-Coffer-1154202795", weight: 4 },
        { name: "Diamond", image: "images/Diamond.png", link: "https://www.deviantart.com/nemeionadmin/art/Diamond-893642549", weight: 5 },
        { name: "Dreadful Drought", image: "images/DreadfulDrought.png", link: "https://www.deviantart.com/nemeionadmin/art/Dreadful-Drought-1048414234", weight: 2 },
        { name: "Eggs", image: "images/Eggs.png", link: "https://www.deviantart.com/nemeionadmin/art/Eggs-893642602", weight: 17 },
        { name: "Elixir of Adonis", image: "images/Adonis.png", link: "https://www.deviantart.com/nemeionadmin/art/Elixir-of-Adonis-893642824", weight: 5 },
        { name: "Elixir of Olympus", image: "images/Olympus.png", link: "https://www.deviantart.com/nemeionadmin/art/Elixir-of-Olympus-893642883", weight: 7 },
        { name: "Emerald", image: "images/Emerald.png", link: "https://www.deviantart.com/nemeionadmin/art/Emerald-893642927", weight: 5 },
        { name: "Emerald Gill", image: "images/EmeraldGill.png", link: "https://www.deviantart.com/nemeionadmin/art/Emerald-Gill-893643864", weight: 14 },
        { name: "Epic Scroll", image: "images/EScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Epic-Scroll-893642761", weight: 3 },
        { name: "Facade of the Caesar", image: "images/Facade.png", link: "https://www.deviantart.com/nemeionadmin/art/Facade-of-the-Caesar-795624271", weight: 6 },
        { name: "Falcon Brown", image: "images/FalconBrown.png", link: "https://www.deviantart.com/nemeionadmin/art/Falcon-Brown-893643102", weight: 1 },
        { name: "Figs", image: "images/Figs.png", link: "https://www.deviantart.com/nemeionadmin/art/Figs-893643273", weight: 15 },
        { name: "Fire Agate", image: "images/FireAgate.png", link: "https://www.deviantart.com/nemeionadmin/art/Fire-Agate-990297709", weight: 2 },
        { name: "Fish Cracker", image: "images/FishCracker.png", link: "https://www.deviantart.com/nemeionadmin/art/Fish-Cracker-893643369", weight: 6 },
        { name: "Fishing Rod", image: "images/FishingRod.png", link: "https://www.deviantart.com/nemeionadmin/art/Fishing-Rod-893643752", weight: 7 },
        { name: "Fragment of Distortion", image: "images/MutationStone.png", link: "https://www.deviantart.com/nemeionadmin/art/Fragment-of-Distortion-668114053", weight: 2 },
        { name: "Fraudlent Pedigree Letter", image: "images/FraudulentPedigree.png", link: "https://www.deviantart.com/nemeionadmin/art/Fraudulent-Pedigree-Letter-1048412698", weight: 2 },
        { name: "Frog Spawn", image: "images/FrogSpawn.png", link: "https://www.deviantart.com/nemeionadmin/art/Frog-Spawn-1149004787", weight: 2 },
        { name: "Ginger", image: "images/Ginger.png", link: "https://www.deviantart.com/nemeionadmin/art/Ginger-893643921", weight: 15 },
        { name: "Glass Bottle", image: "images/GlassBottle.png", link: "https://www.deviantart.com/nemeionadmin/art/Glass-Bottle-862974216", weight: 7 },
        { name: "Glass Jar", image: "images/GlassJar.png", link: "https://www.deviantart.com/nemeionadmin/art/Glass-Jar-893644028", weight: 7 },
        { name: "Gold Ingot", image: "images/GoldIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Gold-Ingot-893644122", weight: 6 },
        { name: "Golden Lotus Potion", image: "images/GoldenLotus.png", link: "https://www.deviantart.com/nemeionadmin/art/Golden-Lotus-Potion-1048419247", weight: 1 },
        { name: "Grain", image: "images/Grain.png", link: "https://www.deviantart.com/nemeionadmin/art/Grain-1148999389", weight: 19 },
        { name: "Grapes", image: "images/Grapes.png", link: "https://www.deviantart.com/nemeionadmin/art/Grapes-893644172", weight: 16 },
        { name: "Grouper", image: "images/Grouper.png", link: "https://www.deviantart.com/nemeionadmin/art/Grouper-893644404", weight: 16 },
        { name: "Hair Dye", image: "images/HairDye.png", link: "https://www.deviantart.com/nemeionadmin/art/Hair-Dye-1037689511", weight: 7 },
        { name: "Hammer", image: "images/Hammer.png", link: "https://www.deviantart.com/nemeionadmin/art/Hammer-893644447", weight: 4 },
        { name: "Haunchmeat", image: "images/Haunchmeat.png", link: "https://www.deviantart.com/nemeionadmin/art/Haunchmeat-893644511", weight: 15 },
        { name: "Hephaestus' Fervor", image: "images/HephFervor.png", link: "https://www.deviantart.com/nemeionadmin/art/Hephaestus-Fervor-893644629", weight: 3 },
        { name: "Herbalist Gloves", image: "images/HerbalistGloves.png", link: "https://www.deviantart.com/nemeionadmin/art/Herbalist-Gloves-1000419301", weight: 4 },
        { name: "Herbal Poultice", image: "images/Poultice.png", link: "https://www.deviantart.com/nemeionadmin/art/Herbal-Poultice-869945917", weight: 5 },
        { name: "Herbs", image: "images/Herbs.png", link: "https://www.deviantart.com/nemeionadmin/art/Herbs-862974581", weight: 18 },
        { name: "Honey Mushrooms", image: "images/HoneyMushrooms.png", link: "https://www.deviantart.com/nemeionadmin/art/Honey-Mushrooms-893646595", weight: 12 },
        { name: "Honeycomb", image: "images/Honeycomb.png", link: "https://www.deviantart.com/nemeionadmin/art/Honeycomb-862974656", weight: 15 },
        { name: "Horse White", image: "images/HorseWhite.png", link: "https://www.deviantart.com/nemeionadmin/art/Horse-White-1106368622", weight: 1 },
        { name: "Hound Points", image: "images/HoundPoints.png", link: "https://www.deviantart.com/nemeionadmin/art/Hound-Points-893644895", weight: 1 },
        { name: "Hyena Tan", image: "images/HyenaTan.png", link: "https://www.deviantart.com/nemeionadmin/art/Hyena-Tan-1106366160", weight: 1 },
        { name: "Ink Black", image: "images/InkBlack.png", link: "https://www.deviantart.com/nemeionadmin/art/Ink-893645160", weight: 9 },
        { name: "Iron Claw Tips", image: "images/IronClaws.png", link: "https://www.deviantart.com/nemeionadmin/art/Iron-Claw-Tips-862975036", weight: 4 },
        { name: "Iron Ingot", image: "images/IronIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Iron-Ingot-893645225", weight: 4 },
        { name: "Ivory Comb", image: "images/IvoryComb.png", link: "https://www.deviantart.com/nemeionadmin/art/Ivory-Comb-862975117", weight: 5 },
        { name: "Jade", image: "images/Jade.png", link: "https://www.deviantart.com/nemeionadmin/art/Jade-937797148", weight: 6 },
        { name: "Jar of Milk", image: "images/MilkJar.png", link: "https://www.deviantart.com/nemeionadmin/art/Jar-of-Milk-990300873", weight: 14 },
        { name: "Jar of Water", image: "images/WaterJar.png", link: "https://www.deviantart.com/nemeionadmin/art/Jar-of-Water-1000416772", weight: 14 },
        { name: "Jerky", image: "images/Jerky.png", link: "https://www.deviantart.com/nemeionadmin/art/Jerky-862975212", weight: 3 },
        { name: "Kopis Sword", image: "images/Kopis.png", link: "https://www.deviantart.com/nemeionadmin/art/Kopis-Sword-862975315", weight: 4 },
        { name: "Large White Pelt", image: "images/LargeWhite.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-White-Pelt-893645535", weight: 4 },
        { name: "Large Black Pelt", image: "images/LargeBlack.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-Black-Pelt-893645510", weight: 4 },
        { name: "Large Cream Pelt", image: "images/LargeCream.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-Cream-Pelt-893645490", weight: 4 },
        { name: "Large Tan Pelt", image: "images/LargeTan.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-Tan-Pelt-893645472", weight: 4 },
        { name: "Large Brown Pelt", image: "images/LargeBrown.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-Brown-Pelt-893645442", weight: 4 },
        { name: "Large Sack of Coins", image: "images/LargeCoins.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-Sack-of-Coins-893645563", weight: 3 },
        { name: "Leather", image: "images/Leather.png", link: "https://www.deviantart.com/nemeionadmin/art/Leather-893645317", weight: 6 },
        { name: "Leather Harness", image: "images/LeatherHarness.png", link: "https://www.deviantart.com/nemeionadmin/art/Leather-Harness-862974334", weight: 6 },
        { name: "Leather Leg Wraps", image: "images/LeatherBracers.png", link: "https://www.deviantart.com/nemeionadmin/art/Leather-Leg-Wraps-862975421", weight: 3 },
        { name: "Leather Strips", image: "images/LeatherStrips.png", link: "https://www.deviantart.com/nemeionadmin/art/Leather-Strips-869942752", weight: 7 },
        { name: "Legendary Scroll", image: "images/LScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Legendary-Scroll-893645688", weight: 1 },
        { name: "Loaded Dice", image: "images/LoadedDice.png", link: "https://www.deviantart.com/nemeionadmin/art/Loaded-Dice-1000413511", weight: 3 },
        { name: "Lost Brute Cub", image: "images/LostBrute.png", link: "https://www.deviantart.com/nemeionadmin/art/Lost-Brute-Cub-893645778", weight: 2 },
        { name: "Lost Regal Cub", image: "images/LostRegal.png", link: "https://www.deviantart.com/nemeionadmin/art/Lost-Regal-Cub-893645840", weight: 2 },
        { name: "Lost Dwarf Cub", image: "images/LostDwarf.png", link: " ", weight: 2 },
        { name: "Lost Domestic Cub", image: "images/LostDom.png", link: " ", weight: 2 },
        { name: "Lynx Piebald", image: "images/LynxPiebald.png", link: "https://www.deviantart.com/nemeionadmin/art/Lynx-Piebald-1057184424", weight: 1 },
        { name: "Lure", image: "images/Lure.png", link: "https://www.deviantart.com/nemeionadmin/art/Lure-893646038", weight: 6 },
        { name: "Lyre", image: "images/Lyre.png", link: "https://www.deviantart.com/nemeionadmin/art/Lyre-869943600", weight: 7 },
        { name: "Map", image: "images/Map.png", link: "https://www.deviantart.com/nemeionadmin/art/Map-893646156", weight: 4 },
        { name: "Mask of Rebirth", image: "images/RebirthMask.png", link: "https://www.deviantart.com/nemeionadmin/art/Mask-of-Rebirth-785110501", weight: 5 },
        { name: "Mask of the Forlorn", image: "images/ForlornMask.png", link: "https://www.deviantart.com/nemeionadmin/art/Mask-of-the-Forlorn-668240778", weight: 6 },
        { name: "Mastiff Albino", image: "images/MastiffAlbino.png", link: "https://www.deviantart.com/nemeionadmin/art/Mastiff-Albino-893646458", weight: 1 },
        { name: "Metal Collar", image: "images/MetalCollar.png", link: "https://www.deviantart.com/nemeionadmin/art/Metal-Collar-869943758", weight: 5 },
        { name: "Metal Pieces", image: "images/MetalPieces.png", link: "https://www.deviantart.com/nemeionadmin/art/Metal-Pieces-869943704", weight: 19 },
        { name: "Metal Supplies", image: "images/MetalSupplies.png", link: "https://www.deviantart.com/nemeionadmin/art/Metal-Supplies-1000417087", weight: 5 },
        { name: "Mirror of Manifestation", image: "images/ManMirror.png", link: "https://www.deviantart.com/nemeionadmin/art/Mirror-of-Manifestation-1037690715", weight: 1 },
        { name: "Missive", image: "images/Missive.png", link: "https://www.deviantart.com/nemeionadmin/art/Missive-990301175", weight: 4 },
        { name: "Mysterious Potion", image: "images/MysteriousPotion.png", link: "https://www.deviantart.com/nemeionadmin/art/Mysterious-Potion-1037689222", weight: 1 },
        { name: "Nails", image: "images/Nails.png", link: "https://www.deviantart.com/nemeionadmin/art/Nails-937796990", weight: 3 },
        { name: "Oats", image: "images/Oats.png", link: "https://www.deviantart.com/nemeionadmin/art/Oats-893646666", weight: 9 },
        { name: "Obsidian", image: "images/Obsidian.png", link: "https://www.deviantart.com/nemeionadmin/art/Obsidian-893646904", weight: 5 },
        { name: "Orangescale Carp", image: "images/OrangeCarp.png", link: "https://www.deviantart.com/nemeionadmin/art/Orangescale-Carp-893648127", weight: 7 },
        { name: "Paper", image: "images/Paper.png", link: "https://www.deviantart.com/nemeionadmin/art/Paper-893646960", weight: 8 },
        { name: "Pearl", image: "images/Pearl.png", link: "https://www.deviantart.com/nemeionadmin/art/Pearl-893647019", weight: 4 },
        { name: "Pegasus White", image: "images/PegasusWhite.png", link: "https://www.deviantart.com/nemeionadmin/art/Pegasus-White-1048400580", weight: 1 },
        { name: "Peridot", image: "images/Peridot.png", link: "https://www.deviantart.com/nemeionadmin/art/Peridot-1048421851", weight: 2 },
        { name: "Pickaxe", image: "images/Pickaxe.png", link: "https://www.deviantart.com/nemeionadmin/art/Pickaxe-893647118", weight: 5 },
        { name: "Pouch of Herbs", image: "images/HerbPouch.png", link: "https://www.deviantart.com/nemeionadmin/art/Pouch-of-Herbs-893647196", weight: 3 },
        { name: "Poseidon's Promise", image: "images/PoseidonsPromise.png", link: "https://www.deviantart.com/nemeionadmin/art/Poseidon-s-Promise-1037688987", weight: 2 },
        { name: "Pouch of Prosperity", image: "images/Prosperity.png", link: "https://www.deviantart.com/nemeionadmin/art/Pouch-of-Prosperity-990300129", weight: 2 },
        { name: "Pumpkin", image: "images/Pumpkin.png", link: "https://www.deviantart.com/nemeionadmin/art/Pumpkin-893647256", weight: 6 },
        { name: "Purple Geode", image: "images/PurpleGeode.png", link: "https://www.deviantart.com/nemeionadmin/art/Purple-Geode-893799912", weight: 5 },
        { name: "Raccoon Grey", image: "images/RaccoonGrey.png", link: "https://www.deviantart.com/nemeionadmin/art/Raccoon-Grey-893647324", weight: 1 },
        { name: "Rare Fabrics", image: "images/RareFabrics.png", link: "https://www.deviantart.com/nemeionadmin/art/Rare-Fabrics-990300520", weight: 4 },
        { name: "Rare Scroll", image: "images/RScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Rare-Scroll-893647526", weight: 3 },
        { name: "Raspberries", image: "images/Raspberries.png", link: "https://www.deviantart.com/nemeionadmin/art/Raspberries-893647578", weight: 8 },
        { name: "Raw Meat", image: "images/RawMeat.png", link: "https://www.deviantart.com/nemeionadmin/art/Raw-Meat-869943888", weight: 7 },
        { name: "Red Currants", image: "images/RedCurrants.png", link: "https://www.deviantart.com/nemeionadmin/art/Red-Currants-862972951", weight: 8 },
        { name: "Red Crystal", image: "images/RedCrystal.png", link: "https://www.deviantart.com/nemeionadmin/art/Red-Crystal-893647621", weight: 6 },
        { name: "Regal Potion", image: "images/RegalPotion.png", link: "https://www.deviantart.com/nemeionadmin/art/Regal-Potion-893647659", weight: 5 },
        { name: "Rejuvenating Salve", image: "images/RejSalve.png", link: "https://www.deviantart.com/nemeionadmin/art/Rejuvenating-Salve-1048417177", weight: 6 },
        { name: "Rhodochrosite", image: "images/Rhodochrosite.png", link: "https://www.deviantart.com/nemeionadmin/art/Rhodochrosite-937796180", weight: 6 },
        { name: "Ring", image: "images/Ring.png", link: "https://www.deviantart.com/nemeionadmin/art/Ring-893786743", weight: 6 },
        { name: "Rope", image: "images/Rope.png", link: "https://www.deviantart.com/nemeionadmin/art/Rope-869944207", weight: 7 },
        { name: "Ruby", image: "images/Ruby.png", link: "https://www.deviantart.com/nemeionadmin/art/Ruby-869944435", weight: 6 },
        { name: "Runestone", image: "images/Runestone.png", link: "https://www.deviantart.com/nemeionadmin/art/Runestone-893647858", weight: 2 },
        { name: "Sands of Time", image: "images/SandsOfTime.png", link: "https://www.deviantart.com/nemeionadmin/art/Sands-of-Time-1037691166", weight: 2 },
        { name: "Sapphire", image: "images/Sapphire.png", link: "https://www.deviantart.com/nemeionadmin/art/Sapphire-869944524", weight: 5 },
        { name: "Satchel", image: "images/Satchel.png", link: "https://www.deviantart.com/nemeionadmin/art/Satchel-893648172", weight: 4 },
        { name: "Scroll in a Bottle", image: "images/BottleScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Scroll-in-a-Bottle-1048423442", weight: 2 },
        { name: "Shank Bone Treat", image: "images/ShankTreat.png", link: "https://www.deviantart.com/nemeionadmin/art/Shank-Bone-Treat-893648243", weight: 7 },
        { name: "Shield", image: "images/Shield.png", link: "https://www.deviantart.com/nemeionadmin/art/Shield-893648529", weight: 4 },
        { name: "Silver Ingot", image: "images/SilverIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Silver-Ingot-893648584", weight: 2 },
        { name: "Small Ingredient Box", image: "images/SmallIngredient.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Ingredient-Box-1154202273", weight: 3 },
        { name: "Small White Pelt", image: "images/SmallWhite.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-White-Pelt-893784323", weight: 7 },
        { name: "Small Cream Pelt", image: "images/SmallCream.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Cream-Pelt-893784276", weight: 7 },
        { name: "Small Tan Pelt", image: "images/SmallTan.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Tan-Pelt-893784302", weight: 7 },
        { name: "Small Brown Pelt", image: "images/SmallBrown.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Brown-Pelt-893784263", weight: 7 },
        { name: "Small Black Pelt", image: "images/SmallBlack.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Black-Pelt-893784191", weight: 7 },
        { name: "Snake Green", image: "images/SnakeGreen.png", link: "https://www.deviantart.com/nemeionadmin/art/Snake-Green-893647470", weight: 1 },
        { name: "Snare", image: "images/Snare.png", link: "https://www.deviantart.com/nemeionadmin/art/Snare-869944565", weight: 5 },
        { name: "Sockeye Salmon", image: "images/Salmon.png", link: "https://www.deviantart.com/nemeionadmin/art/Wild-Salmon-893785418", weight: 8 },
        { name: "Spices", image: "images/Spices.png", link: "https://www.deviantart.com/nemeionadmin/art/Spices-893785043", weight: 8 },
        { name: "Star Ruby", image: "images/StarRuby.png", link: "https://www.deviantart.com/nemeionadmin/art/Star-Ruby-869944706", weight: 3 },
        { name: "Stone Idol", image: "images/StoneIdol.png", link: "https://www.deviantart.com/nemeionadmin/art/Stone-Idol-862974823", weight: 3 },
        { name: "Strange Egg", image: "images/StrangeEgg.png", link: "https://www.deviantart.com/nemeionadmin/art/Strange-Egg-1048406877", weight: 1 },
        { name: "Sunken Treasure Chest", image: "images/Chest2.png", link: "https://www.deviantart.com/nemeionadmin/art/Sunken-Treasure-Chest-893785104", weight: 2 },
        { name: "The Caesar's Dice", image: "images/CaesarsDice.png", link: "https://www.deviantart.com/nemeionadmin/art/The-Caesar-s-dice-795623961", weight: 3 },
        { name: "Thread", image: "images/Thread.png", link: "https://www.deviantart.com/nemeionadmin/art/Thread-893785187", weight: 7 },
        { name: "Tiger's Eye", image: "images/TigersEye.png", link: "https://www.deviantart.com/nemeionadmin/art/Tiger-s-Eye-869944883", weight: 3 },
        { name: "Tincture of Transformation", image: "images/Tincture.png", link: "https://www.deviantart.com/nemeionadmin/art/Tincture-of-Transformation-937796429", weight: 2 },
        { name: "Topaz", image: "images/Topaz.png", link: "https://www.deviantart.com/nemeionadmin/art/Topaz-990295373", weight: 2 },
        { name: "Torch", image: "images/Torch.png", link: "https://www.deviantart.com/nemeionadmin/art/Torch-869945140", weight: 5 },
        { name: "Trait Tome", image: "images/TraitTome.png", link: "https://www.deviantart.com/nemeionadmin/art/Trait-Tome-1149003056", weight: 3 },
        { name: "Trap Netting", image: "images/TrapNetting.png", link: "https://www.deviantart.com/nemeionadmin/art/Trap-Netting-869945444", weight: 6 },
        { name: "Treasure Chest", image: "images/Chest1.png", link: "https://www.deviantart.com/nemeionadmin/art/Treasure-Chest-893785238", weight: 4 },
        { name: "Twine", image: "images/Twine.png", link: "https://www.deviantart.com/nemeionadmin/art/Twine-1000418156", weight: 9 },
        { name: "Uncommon Scroll", image: "images/UScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Uncommon-Scroll-893785302", weight: 4 },
        { name: "Unicorn Meat", image: "images/UnicornMeat.png", link: "https://www.deviantart.com/nemeionadmin/art/Unicorn-Meat-1037691492", weight: 2 },
        { name: "Upgrade Kit II", image: "images/Kit1.png", link: "https://www.deviantart.com/nemeionadmin/art/Upgrade-Kit-Tier-II-821022538", weight: 5 },
        { name: "Upgrade Kit III", image: "images/Kit2.png", link: "https://www.deviantart.com/nemeionadmin/art/Upgrade-Kit-Tier-III-821022605", weight: 3 },
        { name: "Upgrade Kit IV", image: "images/Kit3.png", link: "https://www.deviantart.com/nemeionadmin/art/Upgrade-Kit-Tier-IV-821022672", weight: 2 },
        { name: "Warpaints", image: "images/Warpaints.png", link: "https://www.deviantart.com/nemeionadmin/art/Warpaints-893785368", weight: 7 },
        { name: "Wax", image: "images/Wax.png", link: "https://www.deviantart.com/nemeionadmin/art/Wax-869945413", weight: 7 },
        { name: "Weasel Pine", image: "images/WeaselPine.png", link: "https://www.deviantart.com/nemeionadmin/art/Weasel-Pine-1057182127", weight: 1 },
        { name: "Wicker Basket", image: "images/WickerBasket.png", link: "https://www.deviantart.com/nemeionadmin/art/Wicker-Basket-1149028186", weight: 2 },
        { name: "Wire", image: "images/Wire.png", link: "https://www.deviantart.com/nemeionadmin/art/Wire-869945702", weight: 5 },
        { name: "Wishing Lamp", image: "images/Lamp.png", link: "https://www.deviantart.com/nemeionadmin/art/Wishing-Lamp-1000416215", weight: 1 },
        { name: "Wolf Timber", image: "images/WolfTimber.png", link: "https://www.deviantart.com/nemeionadmin/art/Wolf-Timber-893785656", weight: 1 },
        { name: "Wood Planks", image: "images/WoodPlanks.png", link: "https://www.deviantart.com/nemeionadmin/art/Wooden-Planks-1000415860", weight: 7 },
        { name: "Wooden Bucket", image: "images/WoodBucket.png", link: "https://www.deviantart.com/nemeionadmin/art/Wooden-Bucket-1000416034", weight: 7 },
        { name: "Wooden Log", image: "images/WoodLog.png", link: "https://www.deviantart.com/nemeionadmin/art/Wooden-Log-869945738", weight: 6 },
        { name: "Wooden Trunk", image: "images/WoodTrunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Wooden-Trunk-1000415488",  weight: 2 },
        { name: "Yellow Crystal", image: "images/YellowCrystal.png", link: "https://www.deviantart.com/nemeionadmin/art/Yellow-Crystal-893785808", weight: 6 }
    ],
    backgrounds: [
        { name: "Fields of Love", image: "images/LoveField.png", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Fields-of-Love-1154191432", weight: 2 },
        { name: "Sailing Seas", image: "images/SailingSeas.png", link: "https://www.deviantart.com/nemeionadmin/art/Exclusive-Background-Sailing-Seas-1047716790", weight: 4 },
        { name: "Winter Forest", image: "images/WinterForest.png", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Winter-Forest-998692114", weight: 4 },
        { name: "Haunted Cage", image: "images/HauntedCage.png", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Haunted-Cage-861788466", weight: 6 },
        { name: "Spooky Forest", image: "images/SpookyForest.png", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Spooky-Forest-Halloween-2020-861002050", weight: 6 }
    ],
    harvestcorn: [
        { name: "Corn", image: "images/Corn.png", link: "https://www.deviantart.com/nemeionadmin/art/Corn-1167334952", weight: 99 },
        { name: "Corn", image: "images/Corn.png", link: "https://www.deviantart.com/nemeionadmin/art/Corn-1167334952", weight: 99 }
    ],
    teethbag: [
        { name: "Your x1 Bag of Teeth has revealed x1 Teeth!", weight: 10 },
        { name: "Your x2 Bag of Teeth has revealed x1 Teeth!", weight: 9 },
        { name: "Your x3 Bag of Teeth has revealed x1 Teeth!", weight: 8 },
        { name: "Your x4 Bag of Teeth has revealed x1 Teeth!", weight: 7 },
        { name: "Your x5 Bag of Teeth has revealed x1 Teeth!", weight: 6 },
        { name: "Your x6 Bag of Teeth has revealed x1 Teeth!", weight: 5 },
        { name: "Your x7 Bag of Teeth has revealed x1 Teeth!", weight: 4 },
        { name: "Your x8 Bag of Teeth has revealed x1 Teeth!", weight: 3 },
        { name: "Your x9 Bag of Teeth has revealed x1 Teeth!", weight: 2 },
        { name: "Your x10 Bag of Teeth has revealed x1 Teeth!", weight: 1 },
        { name: "Your x11 Bag of Teeth has revealed x1 Teeth!", weight: 1 },
        { name: "Your x12 Bag of Teeth has revealed x1 Teeth!", weight: 1 },
        { name: "Your x13 Bag of Teeth has revealed x1 Teeth!", weight: 1 },
        { name: "Your x14 Bag of Teeth has revealed x1 Teeth!", weight: 1 },
        { name: "Your x15 Bag of Teeth has revealed x1 Teeth!", weight: 1 }
    ],
    breeding: [
        { name: "Dreadful Drought", image: "images/DreadfulDrought.png", link: "https://www.deviantart.com/nemeionadmin/art/Dreadful-Drought-1048414234", weight: 3 },
        { name: "Unicorn Meat", image: "images/UnicornMeat.png", link: "https://www.deviantart.com/nemeionadmin/art/Unicorn-Meat-1037691492", weight: 2 },
        { name: "Poseidon's Promise", image: "images/PoseidonsPromise.png", link: "https://www.deviantart.com/nemeionadmin/art/Poseidon-s-Promise-1037688987", weight: 1 },
        { name: "Apollo's Feather", image: "images/ApolloFeather.png", link: "https://www.deviantart.com/nemeionadmin/art/Apollo-s-Feather-990294160", weight: 3 },
        { name: "Tincture of Transformation", image: "images/Tincture.png", link: "https://www.deviantart.com/nemeionadmin/art/Tincture-of-Transformation-937796429", weight: 4 },
        { name: "Regal Potion", image: "images/RegalPotion.png", link: "https://www.deviantart.com/nemeionadmin/art/Regal-Potion-893647659", weight: 5 },
        { name: "Hephaestus' Fervor", image: "images/HephFervor.png", link: "https://www.deviantart.com/nemeionadmin/art/Hephaestus-Fervor-893644629", weight: 5 },
        { name: "Brute Potion", image: "images/BrutePotion.png", link: "https://www.deviantart.com/nemeionadmin/art/Brute-Potion-893641009", weight: 5 },
        { name: "Aphrodite's Passion", image: "images/AphroPassion.png", link: "https://www.deviantart.com/nemeionadmin/art/Aphrodite-s-Passion-893639756", weight: 6 },
        { name: "Stone Idol", image: "images/StoneIdol.png", link: "https://www.deviantart.com/nemeionadmin/art/Stone-Idol-862974823", weight: 7 },
        { name: "Blossom of Chloris", image: "images/Chloris.png", link: "https://www.deviantart.com/nemeionadmin/art/Blossom-of-Chloris-668240785", weight: 8 },
        { name: "Fragment of Distortion", image: "images/MutationStone.png", link: "https://www.deviantart.com/nemeionadmin/art/Fragment-of-Distortion-668114053", weight: 2 }
    ],
    decor: [
        { name: "Elixir of Olympus", image: "images/Olympus.png", link: "https://www.deviantart.com/nemeionadmin/art/Elixir-of-Olympus-893642883", weight: 4 },
        { name: "Facade of the Caesar", image: "images/Facade.png", link: "https://www.deviantart.com/nemeionadmin/art/Facade-of-the-Caesar-795624271", weight: 6 },
        { name: "Golden Lotus Potion", image: "images/GoldenLotus.png", link: "https://www.deviantart.com/nemeionadmin/art/Golden-Lotus-Potion-1048419247", weight: 1 },
        { name: "Hair Dye", image: "images/HairDye.png", link: "https://www.deviantart.com/nemeionadmin/art/Hair-Dye-1037689511", weight: 7 },
        { name: "Ivory Comb", image: "images/IvoryComb.png", link: "https://www.deviantart.com/nemeionadmin/art/Ivory-Comb-862975117", weight: 5 },
        { name: "Mask of Rebirth", image: "images/RebirthMask.png", link: "https://www.deviantart.com/nemeionadmin/art/Mask-of-Rebirth-785110501", weight: 5 },
        { name: "Mask of the Forlorn", image: "images/ForlornMask.png", link: "https://www.deviantart.com/nemeionadmin/art/Mask-of-the-Forlorn-668240778", weight: 5 },
        { name: "Tiger's Eye", image: "images/TigersEye.png", link: "https://www.deviantart.com/nemeionadmin/art/Tiger-s-Eye-869944883", weight: 3 },
        { name: "Warpaints", image: "images/Warpaints.png", link: "https://www.deviantart.com/nemeionadmin/art/Warpaints-893785368", weight: 7 }
    ],
    decorationcoffer: [
        { name: "Elixir of Olympus", image: "images/Olympus.png", link: "https://www.deviantart.com/nemeionadmin/art/Elixir-of-Olympus-893642883", weight: 4 },
        { name: "Facade of the Caesar", image: "images/Facade.png", link: "https://www.deviantart.com/nemeionadmin/art/Facade-of-the-Caesar-795624271", weight: 6 },
        { name: "Golden Lotus Potion", image: "images/GoldenLotus.png", link: "https://www.deviantart.com/nemeionadmin/art/Golden-Lotus-Potion-1048419247", weight: 1 },
        { name: "Hair Dye", image: "images/HairDye.png", link: "https://www.deviantart.com/nemeionadmin/art/Hair-Dye-1037689511", weight: 7 },
        { name: "Ivory Comb", image: "images/IvoryComb.png", link: "https://www.deviantart.com/nemeionadmin/art/Ivory-Comb-862975117", weight: 5 },
        { name: "Mask of Rebirth", image: "images/RebirthMask.png", link: "https://www.deviantart.com/nemeionadmin/art/Mask-of-Rebirth-785110501", weight: 5 },
        { name: "Mask of the Forlorn", image: "images/ForlornMask.png", link: "https://www.deviantart.com/nemeionadmin/art/Mask-of-the-Forlorn-668240778", weight: 5 },
        { name: "Tiger's Eye", image: "images/TigersEye.png", link: "https://www.deviantart.com/nemeionadmin/art/Tiger-s-Eye-869944883", weight: 3 },
        { name: "Warpaints", image: "images/Warpaints.png", link: "https://www.deviantart.com/nemeionadmin/art/Warpaints-893785368", weight: 7 }
    ],
    present: [
        { name: "Coal", image: "images/Coal.png", link: "https://www.deviantart.com/nemeionadmin/art/Coal-893641673", weight: 10 },
        { name: "Snowball", image: "images/Snowball.png", link: "https://www.deviantart.com/nemeionadmin/art/Snowball-998662090", weight: 10 },
        { name: "Missive", image: "images/Missive.png", link: "https://www.deviantart.com/nemeionadmin/art/Missive-990301175", weight: 6 },
        { name: "Winter Forest", image: "images/WinterForest.png", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Winter-Forest-998692114", weight: 4 },
        { name: "Rare Fabrics", image: "images/RareFabrics.png", link: "https://www.deviantart.com/nemeionadmin/art/Rare-Fabrics-990300520", weight: 8 },
        { name: "Pouch of Prosperity", image: "images/Prosperity.png", link: "https://www.deviantart.com/nemeionadmin/art/Pouch-of-Prosperity-990300129", weight: 2 },
        { name: "Weasel White", image: "images/WeaselWhite.png", link: "https://www.deviantart.com/nemeionadmin/art/Weasel-White-893785561", weight: 2 },
        { name: "Uncommon Scroll", image: "images/UScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Uncommon-Scroll-893785302", weight: 1 },
        { name: "Sands of Time", image: "images/SandsOfTime.png", link: "https://www.deviantart.com/nemeionadmin/art/Sands-of-Time-1037691166", weight: 2 },
        { name: "Common Scroll", image: "images/CScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Common-Scroll-893641746", weight: 6 },
        { name: "Wolf Arctic", image: "images/WolfArctic.png", link: "https://www.deviantart.com/nemeionadmin/art/Wolf-Arctic-893785734", weight: 2 }
    ],
    metalsupplies: [
        { name: "Anvil", image: "images/Anvil.png", link: "https://www.deviantart.com/nemeionadmin/art/Anvil-893639615", weight: 1 },
        { name: "Chroma Ingot", image: "images/ChromaIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Chroma-Ingot-990297997", weight: 2 },
        { name: "Chunk of Copper", image: "images/CopperChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Copper-893641267", weight: 5 },
        { name: "Iron Ingot", image: "images/IronIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Iron-Ingot-893645225", weight: 4 },
        { name: "Gold Ingot", image: "images/GoldIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Gold-Ingot-893644122", weight: 6 },
        { name: "Wire", image: "images/Wire.png", link: "https://www.deviantart.com/nemeionadmin/art/Wire-869945702", weight: 5 },
        { name: "Hammer", image: "images/Hammer.png", link: "https://www.deviantart.com/nemeionadmin/art/Hammer-893644447", weight: 4 },
        { name: "Nails", image: "images/Nails.png", link: "https://www.deviantart.com/nemeionadmin/art/Nails-937796990", weight: 3 },
        { name: "Chunk of Gold", image: "images/GoldChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Gold-893641299", weight: 4 },
        { name: "Silver Ingot", image: "images/SilverIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Silver-Ingot-893648584", weight: 2 },
        { name: "Chunk of Iron", image: "images/IronChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Iron-893641343", weight: 3 },
        { name: "Metal Collar", image: "images/MetalCollar.png", link: "https://www.deviantart.com/nemeionadmin/art/Metal-Collar-869943758", weight: 5 },
        { name: "Metal Pieces", image: "images/MetalPieces.png", link: "https://www.deviantart.com/nemeionadmin/art/Metal-Pieces-869943704", weight: 9 },
        { name: "Copper Ingot", image: "images/CopperIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Copper-Ingot-893641788", weight: 2 },
        { name: "Chunk of Silver", image: "images/SilverChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Silver-893641392", weight: 2 },
        { name: "Bolts", image: "images/Bolts.png", link: "https://www.deviantart.com/nemeionadmin/art/Bolts-1149001552", weight: 6 }
    ],
    mysterycrate: [
        { name: "Spectral Bonehound Companion", link: "https://www.deviantart.com/nemeionadmin/art/Spectral-Bonehound-Undead-893784851", weight: 50 },
        { name: "Lycan Companion", link: "https://www.deviantart.com/nemeionadmin/art/Lycan-White-1247936572", weight: 50 },
        { name: "Wereworm Companion", link: "https://www.deviantart.com/nemeionadmin/art/Wereworm-Companion-999723203", weight: 20 },
        { name: "Freakish Fangs Blessing", link: "https://www.deviantart.com/nemeionadmin/art/Freakish-Fangs-1247924583", weight: 5 },
        { name: "Stygian Sting Blessing", link: "https://www.deviantart.com/nemeionadmin/art/Stygian-Sting-1247922969", weight: 5 },
        { name: "Mark of the Gorgon Blessing", link: "https://www.deviantart.com/nemeionadmin/art/Mark-of-the-Gorgon-1247921681", weight: 5 },
        { name: "Medusa's Malice Blessing", link: "https://www.deviantart.com/nemeionadmin/art/Medusa-s-Malice-1247936681", weight: 5 },
        { name: "Cursed Tome", link: "https://www.deviantart.com/nemeionadmin/art/Cursed-Tome-1247920198", weight: 3 },
        { name: "Cursed Blood of Hades", link: "https://www.deviantart.com/nemeionadmin/art/Cursed-Blood-of-Hades-1247919508", weight: 5 },
        { name: "Blistering Bile Blessing", link: "https://www.deviantart.com/nemeionadmin/art/Blistering-Bile-1137290581", weight: 10 },
        { name: "Spooky Forest Background", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Spooky-Forest-Halloween-2020-861002050", weight: 50 },
        { name: "Haunted Cage Background", link: "https://www.deviantart.com/nemeionadmin/art/Import-Background-Haunted-Cage-861788466", weight: 50 },
        { name: "Blistering Bile Blessing", link: "https://www.deviantart.com/nemeionadmin/art/Blistering-Bile-1137290581", weight: 10 },
        { name: "Cryptic Curse Trait", link: "https://www.deviantart.com/nemeionadmin/art/Cryptic-Curse-990293796", weight: 15 },
    ],
    mysterypotion: [
        { name: "Enchanted Necklace", weight: 10 },
        { name: "Mystic Scroll", weight: 18 },
        { name: "Magic Boots", weight: 12 },
        { name: "Eldritch Ring", weight: 15 },
        { name: "Warding Charm", weight: 10 }
    ],
    scrolls: [
        { name: "Common Scroll", image: "images/CScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Common-Scroll-893641746", weight: 10 },
        { name: "Uncommon Scroll", image: "images/UScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Uncommon-Scroll-893785302", weight: 8 },
        { name: "Rare Scroll", image: "images/RScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Rare-Scroll-893647526", weight: 7 },
        { name: "Epic Scroll", image: "images/EScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Epic-Scroll-893642761", weight: 5 },
        { name: "Legendary Scroll", image: "images/LScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Legendary-Scroll-893645688", weight: 1 }
    ],
    smallingredient: [
        { name: "Wire", image: "images/Wire.png", link: "https://www.deviantart.com/nemeionadmin/art/Wire-869945702", weight: 5 },
        { name: "Alcohol", image: "images/Alcohol.png", link: "https://www.deviantart.com/nemeionadmin/art/Alcohol-937794821", weight: 9 },
        { name: "Chunk of Copper", image: "images/CopperChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Copper-893641267", weight: 5 },
        { name: "Chunk of Gold", image: "images/GoldChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Gold-893641299", weight: 4 },
        { name: "Chunk of Iron", image: "images/IronChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Iron-893641343", weight: 3 },
        { name: "Chunk of Silver", image: "images/SilverChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Silver-893641392", weight: 2 },
        { name: "Wax", image: "images/Wax.png", link: "https://www.deviantart.com/nemeionadmin/art/Wax-869945413", weight: 7 },
        { name: "Grain", image: "images/Grain.png", link: "https://www.deviantart.com/nemeionadmin/art/Grain-1148999389", weight: 9 },
        { name: "Grapes", image: "images/Grapes.png", link: "https://www.deviantart.com/nemeionadmin/art/Grapes-893644172", weight: 9 },
        { name: "Grouper", image: "images/Grouper.png", link: "https://www.deviantart.com/nemeionadmin/art/Grouper-893644404", weight: 6 },
        { name: "Coffee Beans", image: "images/CoffeeBeans.png", link: "https://www.deviantart.com/nemeionadmin/art/Coffee-Beans-1149001000", weight: 7 },
        { name: "Emerald Gill", image: "images/EmeraldGill.png", link: "https://www.deviantart.com/nemeionadmin/art/Emerald-Gill-893643864", weight: 8 },
        { name: "Figs", image: "images/Figs.png", link: "https://www.deviantart.com/nemeionadmin/art/Figs-893643273", weight: 8 },
        { name: "Herbs", image: "images/Herbs.png", link: "https://www.deviantart.com/nemeionadmin/art/Herbs-862974581", weight: 8 },
        { name: "Ginger", image: "images/Ginger.png", link: "https://www.deviantart.com/nemeionadmin/art/Ginger-893643921", weight: 5 },
        { name: "Haunchmeat", image: "images/Haunchmeat.png", link: "https://www.deviantart.com/nemeionadmin/art/Haunchmeat-893644511", weight: 5 },
        { name: "Honey Mushrooms", image: "images/HoneyMushrooms.png", link: "https://www.deviantart.com/nemeionadmin/art/Honey-Mushrooms-893646595", weight: 10 },
        { name: "Honeycomb", image: "images/Honeycomb.png", link: "https://www.deviantart.com/nemeionadmin/art/Honeycomb-862974656", weight: 5 },
        { name: "Twine", image: "images/Twine.png", link: "https://www.deviantart.com/nemeionadmin/art/Twine-1000418156", weight: 9 },
        { name: "Spices", image: "images/Spices.png", link: "https://www.deviantart.com/nemeionadmin/art/Spices-893785043", weight: 8 },
        { name: "Nails", image: "images/Nails.png", link: "https://www.deviantart.com/nemeionadmin/art/Nails-937796990", weight: 3 },
        { name: "Leather", image: "images/Leather.png", link: "https://www.deviantart.com/nemeionadmin/art/Leather-893645317", weight: 6 },
        { name: "Large White Pelt", image: "images/LargeWhite.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-White-Pelt-893645535", weight: 4 },
        { name: "Large Black Pelt", image: "images/LargeBlack.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-Black-Pelt-893645510", weight: 4 },
        { name: "Large Cream Pelt", image: "images/LargeCream.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-Cream-Pelt-893645490", weight: 4 },
        { name: "Large Tan Pelt", image: "images/LargeTan.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-Tan-Pelt-893645472", weight: 4 },
        { name: "Large Brown Pelt", image: "images/LargeBrown.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-Brown-Pelt-893645442", weight: 4 },
        { name: "Oats", image: "images/Oats.png", link: "https://www.deviantart.com/nemeionadmin/art/Oats-893646666", weight: 9 },
        { name: "Metal Pieces", image: "images/MetalPieces.png", link: "https://www.deviantart.com/nemeionadmin/art/Metal-Pieces-869943704", weight: 9 },
        { name: "Obsidian", image: "images/Obsidian.png", link: "https://www.deviantart.com/nemeionadmin/art/Obsidian-893646904", weight: 5 },
        { name: "Orangescale Carp", image: "images/OrangeCarp.png", link: "https://www.deviantart.com/nemeionadmin/art/Orangescale-Carp-893648127", weight: 7 },
        { name: "Leather Strips", image: "images/LeatherStrips.png", link: "https://www.deviantart.com/nemeionadmin/art/Leather-Strips-869942752", weight: 7 },
        { name: "Paper", image: "images/Paper.png", link: "https://www.deviantart.com/nemeionadmin/art/Paper-893646960", weight: 8 },
        { name: "Silver Ingot", image: "images/SilverIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Silver-Ingot-893648584", weight: 2 },
        { name: "Pumpkin", image: "images/Pumpkin.png", link: "https://www.deviantart.com/nemeionadmin/art/Pumpkin-893647256", weight: 6 },
        { name: "Small White Pelt", image: "images/SmallWhite.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-White-Pelt-893784323", weight: 7 },
        { name: "Small Cream Pelt", image: "images/SmallCream.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Cream-Pelt-893784276", weight: 7 },
        { name: "Small Tan Pelt", image: "images/SmallTan.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Tan-Pelt-893784302", weight: 7 },
        { name: "Raspberries", image: "images/Raspberries.png", link: "https://www.deviantart.com/nemeionadmin/art/Raspberries-893647578", weight: 8 },
        { name: "Raw Meat", image: "images/RawMeat.png", link: "https://www.deviantart.com/nemeionadmin/art/Raw-Meat-869943888", weight: 7 },
        { name: "Red Currants", image: "images/RedCurrants.png", link: "https://www.deviantart.com/nemeionadmin/art/Red-Currants-862972951", weight: 8 },
        { name: "Small Brown Pelt", image: "images/SmallBrown.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Brown-Pelt-893784263", weight: 7 },
        { name: "Small Black Pelt", image: "images/SmallBlack.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Black-Pelt-893784191", weight: 7 },
        { name: "Thread", image: "images/Thread.png", link: "https://www.deviantart.com/nemeionadmin/art/Thread-893785187", weight: 7 }
    ],
    sunkenchest: [
        { name: "Ancient Tablet", image: "images/AncientTablet.png", link: "https://www.deviantart.com/nemeionadmin/art/Ancient-Tablet-1048407956", weight: 3 },
        { name: "Ancient Time Scroll", image: "images/AncientTimeScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Ancient-Time-Scroll-1154720381", weight: 2 },
        { name: "Anthea's Vase", image: "images/AntheaVase.png", link: "https://www.deviantart.com/nemeionadmin/art/Anthea-s-Vase-1048408927", weight: 4 },
        { name: "Anvil", image: "images/Anvil.png", link: "https://www.deviantart.com/nemeionadmin/art/Anvil-893639615", weight: 3 },
        { name: "Aphrodite's Lament", image: "images/AphroLament.png", link: "https://www.deviantart.com/nemeionadmin/art/Aphrodite-s-Lament-1048409662", weight: 3 },
        { name: "Aphrodite's Passion", image: "images/AphroPassion.png", link: "https://www.deviantart.com/nemeionadmin/art/Aphrodite-s-Passion-893639756", weight: 4 },
        { name: "Apollo's Feather", image: "images/ApolloFeather.png", link: "https://www.deviantart.com/nemeionadmin/art/Apollo-s-Feather-990294160", weight: 2 },
        { name: "Arrows", image: "images/Arrows.png", link: "https://www.deviantart.com/nemeionadmin/art/Arrows-862972674", weight: 7 },
        { name: "Axe", image: "images/Axe.png", link: "https://www.deviantart.com/nemeionadmin/art/Axe-893639834", weight: 7 },
        { name: "Befuddling Brew", image: "images/BefuddlingBrew.png", link: "https://www.deviantart.com/nemeionadmin/art/Befuddling-Brew-1156343809", weight: 1 },
        { name: "Blessing of Hera", image: "images/HeraBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Hera-1000420405", weight: 1 },
        { name: "Blessing of Poseidon", image: "images/PoseidonBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Poseidon-990292572", weight: 1 },
        { name: "Blessing of Volcan", image: "images/VolcanBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Volcan-990292998", weight: 1 },
        { name: "Blessing of Zeus", image: "images/ZeusBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Zeus-1000420032", weight: 1 },
        { name: "Blistering Bile", image: "images/BlisteringBile.png", link: "https://www.deviantart.com/nemeionadmin/art/Blistering-Bile-1137290581", weight: 1 },
        { name: "Bloodstone", image: "images/Bloodstone.png", link: "https://www.deviantart.com/nemeionadmin/art/Bloodstone-893640348", weight: 3 },
        { name: "Blossom of Chloris", image: "images/Chloris.png", link: "https://www.deviantart.com/nemeionadmin/art/Blossom-of-Chloris-668240785", weight: 5 },
        { name: "Blue Crystal", image: "images/BlueCrystal.png", link: "https://www.deviantart.com/nemeionadmin/art/Blue-Crystal-893640417", weight: 6 },
        { name: "Blue Geode", image: "images/BlueGeode.png", link: "https://www.deviantart.com/nemeionadmin/art/Blue-Geode-893799887", weight: 6 },
        { name: "Bolts", image: "images/Bolts.png", link: "https://www.deviantart.com/nemeionadmin/art/Bolts-1149001552", weight: 6 },
        { name: "Bottled Lightning", image: "images/BottledLightning.png", link: "https://www.deviantart.com/nemeionadmin/art/Bottled-Lightning-990293347", weight: 1 },
        { name: "Bountiful Tonic", image: "images/BountifulTonic.png", link: "https://www.deviantart.com/nemeionadmin/art/Bountiful-Tonic-1048415748", weight: 3 },
        { name: "Bow", image: "images/Bow.png", link: "https://www.deviantart.com/nemeionadmin/art/Bow-893640484", weight: 6 },
        { name: "Brute Potion", image: "images/BrutePotion.png", link: "https://www.deviantart.com/nemeionadmin/art/Brute-Potion-893641009", weight: 3 },
        { name: "Chalice", image: "images/Chalice.png", link: "https://www.deviantart.com/nemeionadmin/art/Chalice-893641224", weight: 5 },
        { name: "Chunk of Azurite", image: "images/AzuriteChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Azurite-990298338", weight: 3 },
        { name: "Chunk of Copper", image: "images/CopperChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Copper-893641267", weight: 5 },
        { name: "Chunk of Gold", image: "images/GoldChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Gold-893641299", weight: 4 },
        { name: "Chunk of Iron", image: "images/IronChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Iron-893641343", weight: 3 },
        { name: "Chunk of Silver", image: "images/SilverChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Silver-893641392", weight: 2 },
        { name: "Chunk of Unakite", image: "images/UnakiteChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Unakite-990298579", weight: 4 },
        { name: "Clan Creation Deed", image: "images/ClanDeed.png", link: "https://www.deviantart.com/nemeionadmin/art/Clan-Creation-Deed-869944958", weight: 7 },
        { name: "Cluster of Gems", image: "images/GemCluster.png", link: "https://www.deviantart.com/nemeionadmin/art/Cluster-of-Gems-990299363", weight: 2 },
        { name: "Common Scroll", image: "images/CScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Common-Scroll-893641746", weight: 2 },
        { name: "Copper Ingot", image: "images/CopperIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Copper-Ingot-893641788", weight: 2 },
        { name: "Diamond", image: "images/Diamond.png", link: "https://www.deviantart.com/nemeionadmin/art/Diamond-893642549", weight: 5 },
        { name: "Dreadful Drought", image: "images/DreadfulDrought.png", link: "https://www.deviantart.com/nemeionadmin/art/Dreadful-Drought-1048414234", weight: 2 },
        { name: "Elixir of Adonis", image: "images/Adonis.png", link: "https://www.deviantart.com/nemeionadmin/art/Elixir-of-Adonis-893642824", weight: 5 },
        { name: "Elixir of Olympus", image: "images/Olympus.png", link: "https://www.deviantart.com/nemeionadmin/art/Elixir-of-Olympus-893642883", weight: 7 },
        { name: "Emerald", image: "images/Emerald.png", link: "https://www.deviantart.com/nemeionadmin/art/Emerald-893642927", weight: 5 },
        { name: "Emerald Gill", image: "images/EmeraldGill.png", link: "https://www.deviantart.com/nemeionadmin/art/Emerald-Gill-893643864", weight: 8 },
        { name: "Epic Scroll", image: "images/EScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Epic-Scroll-893642761", weight: 3 },
        { name: "Facade of the Caesar", image: "images/Facade.png", link: "https://www.deviantart.com/nemeionadmin/art/Facade-of-the-Caesar-795624271", weight: 6 },
        { name: "Fire Agate", image: "images/FireAgate.png", link: "https://www.deviantart.com/nemeionadmin/art/Fire-Agate-990297709", weight: 2 },
        { name: "Fish Cracker", image: "images/FishCracker.png", link: "https://www.deviantart.com/nemeionadmin/art/Fish-Cracker-893643369", weight: 6 },
        { name: "Fishing Rod", image: "images/FishingRod.png", link: "https://www.deviantart.com/nemeionadmin/art/Fishing-Rod-893643752", weight: 7 },
        { name: "Fragment of Distortion", image: "images/MutationStone.png", link: "https://www.deviantart.com/nemeionadmin/art/Fragment-of-Distortion-668114053", weight: 2 },
        { name: "Fraudlent Pedigree Letter", image: "images/FraudulentPedigree.png", link: "https://www.deviantart.com/nemeionadmin/art/Fraudulent-Pedigree-Letter-1048412698", weight: 2 },
        { name: "Grouper", image: "images/Grouper.png", link: "https://www.deviantart.com/nemeionadmin/art/Grouper-893644404", weight: 6 },
        { name: "Hair Dye", image: "images/HairDye.png", link: "https://www.deviantart.com/nemeionadmin/art/Hair-Dye-1037689511", weight: 7 },
        { name: "Hammer", image: "images/Hammer.png", link: "https://www.deviantart.com/nemeionadmin/art/Hammer-893644447", weight: 4 },
        { name: "Mask of Rebirth", image: "images/RebirthMask.png", link: "https://www.deviantart.com/nemeionadmin/art/Mask-of-Rebirth-785110501", weight: 5 },
        { name: "Mask of the Forlorn", image: "images/ForlornMask.png", link: "https://www.deviantart.com/nemeionadmin/art/Mask-of-the-Forlorn-668240778", weight: 6 },
        { name: "Mysterious Potion", image: "images/MysteriousPotion.png", link: "https://www.deviantart.com/nemeionadmin/art/Mysterious-Potion-1037689222", weight: 1 },
        { name: "Pearl", image: "images/Pearl.png", link: "https://www.deviantart.com/nemeionadmin/art/Pearl-893647019", weight: 4 },
        { name: "Poseidon's Promise", image: "images/PoseidonsPromise.png", link: "https://www.deviantart.com/nemeionadmin/art/Poseidon-s-Promise-1037688987", weight: 2 },
        { name: "Sockeye Salmon", image: "images/Salmon.png", link: "https://www.deviantart.com/nemeionadmin/art/Wild-Salmon-893785418", weight: 8 },
        { name: "Trap Netting", image: "images/TrapNetting.png", link: "https://www.deviantart.com/nemeionadmin/art/Trap-Netting-869945444", weight: 6 },
        { name: "Wood Planks", image: "images/WoodPlanks.png", link: "https://www.deviantart.com/nemeionadmin/art/Wooden-Planks-1000415860", weight: 7 },
        { name: "Wooden Bucket", image: "images/WoodBucket.png", link: "https://www.deviantart.com/nemeionadmin/art/Wooden-Bucket-1000416034", weight: 7 },
        { name: "Wooden Log", image: "images/WoodLog.png", link: "https://www.deviantart.com/nemeionadmin/art/Wooden-Log-869945738", weight: 6 }
    ],
    treasurechest: [
        { name: "Ancient Tablet", image: "images/AncientTablet.png", link: "https://www.deviantart.com/nemeionadmin/art/Ancient-Tablet-1048407956", weight: 30 },
        { name: "Ancient Time Scroll", image: "images/AncientTimeScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Ancient-Time-Scroll-1154720381", weight: 15 },
        { name: "Anthea's Vase", image: "images/AntheaVase.png", link: "https://www.deviantart.com/nemeionadmin/art/Anthea-s-Vase-1048408927", weight: 4 },
        { name: "Anvil", image: "images/Anvil.png", link: "https://www.deviantart.com/nemeionadmin/art/Anvil-893639615", weight: 30 },
        { name: "Aphrodite's Lament", image: "images/AphroLament.png", link: "https://www.deviantart.com/nemeionadmin/art/Aphrodite-s-Lament-1048409662", weight: 5 },
        { name: "Aphrodite's Passion", image: "images/AphroPassion.png", link: "https://www.deviantart.com/nemeionadmin/art/Aphrodite-s-Passion-893639756", weight: 15 },
        { name: "Apollo's Feather", image: "images/ApolloFeather.png", link: "https://www.deviantart.com/nemeionadmin/art/Apollo-s-Feather-990294160", weight: 2 },
        { name: "Arrows", image: "images/Arrows.png", link: "https://www.deviantart.com/nemeionadmin/art/Arrows-862972674", weight: 35 },
        { name: "Axe", image: "images/Axe.png", link: "https://www.deviantart.com/nemeionadmin/art/Axe-893639834", weight: 35 },
        { name: "Bandages", image: "images/Bandages.png", link: "https://www.deviantart.com/nemeionadmin/art/Bandages-893640088", weight: 70 },
        { name: "Befuddling Brew", image: "images/BefuddlingBrew.png", link: "https://www.deviantart.com/nemeionadmin/art/Befuddling-Brew-1156343809", weight: 1 },
        { name: "Black Currants", image: "images/BlackCurrants.png", link: "https://www.deviantart.com/nemeionadmin/art/Black-Currants-862973108", weight: 60 },
        { name: "Blessing of Hera", image: "images/HeraBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Hera-1000420405", weight: 1 },
        { name: "Blessing of Poseidon", image: "images/PoseidonBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Poseidon-990292572", weight: 1 },
        { name: "Blessing of Volcan", image: "images/VolcanBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Volcan-990292998", weight: 1 },
        { name: "Blessing of Zeus", image: "images/ZeusBlessing.png", link: "https://www.deviantart.com/nemeionadmin/art/Blessing-of-Zeus-1000420032", weight: 1 },
        { name: "Blistering Bile", image: "images/BlisteringBile.png", link: "https://www.deviantart.com/nemeionadmin/art/Blistering-Bile-1137290581", weight: 1 },
        { name: "Bloodstone", image: "images/Bloodstone.png", link: "https://www.deviantart.com/nemeionadmin/art/Bloodstone-893640348", weight: 30 },
        { name: "Blossom of Chloris", image: "images/Chloris.png", link: "https://www.deviantart.com/nemeionadmin/art/Blossom-of-Chloris-668240785", weight: 50 },
        { name: "Blue Crystal", image: "images/BlueCrystal.png", link: "https://www.deviantart.com/nemeionadmin/art/Blue-Crystal-893640417", weight: 60 },
        { name: "Blue Geode", image: "images/BlueGeode.png", link: "https://www.deviantart.com/nemeionadmin/art/Blue-Geode-893799887", weight: 60 },
        { name: "Bottled Lightning", image: "images/BottledLightning.png", link: "https://www.deviantart.com/nemeionadmin/art/Bottled-Lightning-990293347", weight: 1 },
        { name: "Bountiful Tonic", image: "images/BountifulTonic.png", link: "https://www.deviantart.com/nemeionadmin/art/Bountiful-Tonic-1048415748", weight: 30 },
        { name: "Bow", image: "images/Bow.png", link: "https://www.deviantart.com/nemeionadmin/art/Bow-893640484", weight: 45 },
        { name: "Brute Potion", image: "images/BrutePotion.png", link: "https://www.deviantart.com/nemeionadmin/art/Brute-Potion-893641009", weight: 35 },
        { name: "Chalice", image: "images/Chalice.png", link: "https://www.deviantart.com/nemeionadmin/art/Chalice-893641224", weight: 5 },
        { name: "Champion's Blade", image: "images/ChampionBlade.png", link: "https://www.deviantart.com/nemeionadmin/art/Champion-s-Blade-795623439", weight: 60 },
        { name: "Chroma Ingot", image: "images/ChromaIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Chroma-Ingot-990297997", weight: 10 },
        { name: "Chunk of Azurite", image: "images/AzuriteChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Azurite-990298338", weight: 3 },
        { name: "Chunk of Copper", image: "images/CopperChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Copper-893641267", weight: 15 },
        { name: "Chunk of Gold", image: "images/GoldChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Gold-893641299", weight: 15 },
        { name: "Chunk of Iron", image: "images/IronChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Iron-893641343", weight: 15 },
        { name: "Chunk of Silver", image: "images/SilverChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Silver-893641392", weight: 15 },
        { name: "Chunk of Unakite", image: "images/UnakiteChunk.png", link: "https://www.deviantart.com/nemeionadmin/art/Chunk-of-Unakite-990298579", weight: 4 },
        { name: "Clan Creation Deed", image: "images/ClanDeed.png", link: "https://www.deviantart.com/nemeionadmin/art/Clan-Creation-Deed-869944958", weight: 7 },
        { name: "Cluster of Gems", image: "images/GemCluster.png", link: "https://www.deviantart.com/nemeionadmin/art/Cluster-of-Gems-990299363", weight: 2 },
        { name: "Common Scroll", image: "images/CScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Common-Scroll-893641746", weight: 2 },
        { name: "Copper Ingot", image: "images/CopperIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Copper-Ingot-893641788", weight: 2 },
        { name: "Creature Crate", image: "images/CreatureCrate.png", link: "https://www.deviantart.com/nemeionadmin/art/Creature-Crate-893641939", weight: 5 },
        { name: "Diamond", image: "images/Diamond.png", link: "https://www.deviantart.com/nemeionadmin/art/Diamond-893642549", weight: 5 },
        { name: "Dreadful Drought", image: "images/DreadfulDrought.png", link: "https://www.deviantart.com/nemeionadmin/art/Dreadful-Drought-1048414234", weight: 2 },
        { name: "Elixir of Adonis", image: "images/Adonis.png", link: "https://www.deviantart.com/nemeionadmin/art/Elixir-of-Adonis-893642824", weight: 5 },
        { name: "Elixir of Olympus", image: "images/Olympus.png", link: "https://www.deviantart.com/nemeionadmin/art/Elixir-of-Olympus-893642883", weight: 7 },
        { name: "Emerald", image: "images/Emerald.png", link: "https://www.deviantart.com/nemeionadmin/art/Emerald-893642927", weight: 5 },
        { name: "Epic Scroll", image: "images/EScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Epic-Scroll-893642761", weight: 3 },
        { name: "Facade of the Caesar", image: "images/Facade.png", link: "https://www.deviantart.com/nemeionadmin/art/Facade-of-the-Caesar-795624271", weight: 45 },
        { name: "Fire Agate", image: "images/FireAgate.png", link: "https://www.deviantart.com/nemeionadmin/art/Fire-Agate-990297709", weight: 2 },
        { name: "Fish Cracker", image: "images/FishCracker.png", link: "https://www.deviantart.com/nemeionadmin/art/Fish-Cracker-893643369", weight: 2 },
        { name: "Fishing Rod", image: "images/FishingRod.png", link: "https://www.deviantart.com/nemeionadmin/art/Fishing-Rod-893643752", weight: 35 },
        { name: "Fragment of Distortion", image: "images/MutationStone.png", link: "https://www.deviantart.com/nemeionadmin/art/Fragment-of-Distortion-668114053", weight: 2 },
        { name: "Fraudlent Pedigree Letter", image: "images/FraudulentPedigree.png", link: "https://www.deviantart.com/nemeionadmin/art/Fraudulent-Pedigree-Letter-1048412698", weight: 20 },
        { name: "Gold Ingot", image: "images/GoldIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Gold-Ingot-893644122", weight: 6 },
        { name: "Golden Lotus Potion", image: "images/GoldenLotus.png", link: "https://www.deviantart.com/nemeionadmin/art/Golden-Lotus-Potion-1048419247", weight: 1 },
        { name: "Hair Dye", image: "images/HairDye.png", link: "https://www.deviantart.com/nemeionadmin/art/Hair-Dye-1037689511", weight: 40 },
        { name: "Hammer", image: "images/Hammer.png", link: "https://www.deviantart.com/nemeionadmin/art/Hammer-893644447", weight: 45 },
        { name: "Hephaestus' Fervor", image: "images/HephFervor.png", link: "https://www.deviantart.com/nemeionadmin/art/Hephaestus-Fervor-893644629", weight: 3 },
        { name: "Herbalist Gloves", image: "images/HerbalistGloves.png", link: "https://www.deviantart.com/nemeionadmin/art/Herbalist-Gloves-1000419301", weight: 35 },
        { name: "Herbal Poultice", image: "images/Poultice.png", link: "https://www.deviantart.com/nemeionadmin/art/Herbal-Poultice-869945917", weight: 50 },
        { name: "Ink Black", image: "images/InkBlack.png", link: "https://www.deviantart.com/nemeionadmin/art/Ink-893645160", weight: 80 },
        { name: "Iron Claw Tips", image: "images/IronClaws.png", link: "https://www.deviantart.com/nemeionadmin/art/Iron-Claw-Tips-862975036", weight: 35 },
        { name: "Iron Ingot", image: "images/IronIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Iron-Ingot-893645225", weight: 4 },
        { name: "Ivory Comb", image: "images/IvoryComb.png", link: "https://www.deviantart.com/nemeionadmin/art/Ivory-Comb-862975117", weight: 25 },
        { name: "Jade", image: "images/Jade.png", link: "https://www.deviantart.com/nemeionadmin/art/Jade-937797148", weight: 50 },
        { name: "Kopis Sword", image: "images/Kopis.png", link: "https://www.deviantart.com/nemeionadmin/art/Kopis-Sword-862975315", weight: 25 },
        { name: "Large Sack of Coins", image: "images/LargeCoins.png", link: "https://www.deviantart.com/nemeionadmin/art/Large-Sack-of-Coins-893645563", weight: 30 },
        { name: "Legendary Scroll", image: "images/LScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Legendary-Scroll-893645688", weight: 1 },
        { name: "Loaded Dice", image: "images/LoadedDice.png", link: "https://www.deviantart.com/nemeionadmin/art/Loaded-Dice-1000413511", weight: 25 },
        { name: "Lost Brute Cub", image: "images/LostBrute.png", link: "https://www.deviantart.com/nemeionadmin/art/Lost-Brute-Cub-893645778", weight: 25 },
        { name: "Lost Regal Cub", image: "images/LostRegal.png", link: "https://www.deviantart.com/nemeionadmin/art/Lost-Regal-Cub-893645840", weight: 15 },
        { name: "Lure", image: "images/Lure.png", link: "https://www.deviantart.com/nemeionadmin/art/Lure-893646038", weight: 35 },
        { name: "Mask of Rebirth", image: "images/RebirthMask.png", link: "https://www.deviantart.com/nemeionadmin/art/Mask-of-Rebirth-785110501", weight: 15 },
        { name: "Mask of the Forlorn", image: "images/ForlornMask.png", link: "https://www.deviantart.com/nemeionadmin/art/Mask-of-the-Forlorn-668240778", weight: 20 },
        { name: "Metal Collar", image: "images/MetalCollar.png", link: "https://www.deviantart.com/nemeionadmin/art/Metal-Collar-869943758", weight: 5 },
        { name: "Metal Pieces", image: "images/MetalPieces.png", link: "https://www.deviantart.com/nemeionadmin/art/Metal-Pieces-869943704", weight: 80 },
        { name: "Mirror of Manifestation", image: "images/ManMirror.png", link: "https://www.deviantart.com/nemeionadmin/art/Mirror-of-Manifestation-1037690715", weight: 1 },
        { name: "Missive", image: "images/Missive.png", link: "https://www.deviantart.com/nemeionadmin/art/Missive-990301175", weight: 20 },
        { name: "Mysterious Potion", image: "images/MysteriousPotion.png", link: "https://www.deviantart.com/nemeionadmin/art/Mysterious-Potion-1037689222", weight: 15 },
        { name: "Nails", image: "images/Nails.png", link: "https://www.deviantart.com/nemeionadmin/art/Nails-937796990", weight: 30 },
        { name: "Peridot", image: "images/Peridot.png", link: "https://www.deviantart.com/nemeionadmin/art/Peridot-1048421851", weight: 2 },
        { name: "Pickaxe", image: "images/Pickaxe.png", link: "https://www.deviantart.com/nemeionadmin/art/Pickaxe-893647118", weight: 35 },
        { name: "Pouch of Herbs", image: "images/HerbPouch.png", link: "https://www.deviantart.com/nemeionadmin/art/Pouch-of-Herbs-893647196", weight: 30 },
        { name: "Poseidon's Promise", image: "images/PoseidonsPromise.png", link: "https://www.deviantart.com/nemeionadmin/art/Poseidon-s-Promise-1037688987", weight: 2 },
        { name: "Pouch of Prosperity", image: "images/Prosperity.png", link: "https://www.deviantart.com/nemeionadmin/art/Pouch-of-Prosperity-990300129", weight: 2 },
        { name: "Purple Geode", image: "images/PurpleGeode.png", link: "https://www.deviantart.com/nemeionadmin/art/Purple-Geode-893799912", weight: 25 },
        { name: "Rare Fabrics", image: "images/RareFabrics.png", link: "https://www.deviantart.com/nemeionadmin/art/Rare-Fabrics-990300520", weight: 40 },
        { name: "Rare Scroll", image: "images/RScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Rare-Scroll-893647526", weight: 3 },
        { name: "Regal Potion", image: "images/RegalPotion.png", link: "https://www.deviantart.com/nemeionadmin/art/Regal-Potion-893647659", weight: 5 },
        { name: "Rejuvenating Salve", image: "images/RejSalve.png", link: "https://www.deviantart.com/nemeionadmin/art/Rejuvenating-Salve-1048417177", weight: 35 },
        { name: "Rhodochrosite", image: "images/Rhodochrosite.png", link: "https://www.deviantart.com/nemeionadmin/art/Rhodochrosite-937796180", weight: 50 },
        { name: "Ring", image: "images/Ring.png", link: "https://www.deviantart.com/nemeionadmin/art/Ring-893786743", weight: 25 },
        { name: "Rope", image: "images/Rope.png", link: "https://www.deviantart.com/nemeionadmin/art/Rope-869944207", weight: 35 },
        { name: "Ruby", image: "images/Ruby.png", link: "https://www.deviantart.com/nemeionadmin/art/Ruby-869944435", weight: 55 },
        { name: "Runestone", image: "images/Runestone.png", link: "https://www.deviantart.com/nemeionadmin/art/Runestone-893647858", weight: 2 },
        { name: "Sands of Time", image: "images/SandsOfTime.png", link: "https://www.deviantart.com/nemeionadmin/art/Sands-of-Time-1037691166", weight: 10 },
        { name: "Sapphire", image: "images/Sapphire.png", link: "https://www.deviantart.com/nemeionadmin/art/Sapphire-869944524", weight: 35 },
        { name: "Satchel", image: "images/Satchel.png", link: "https://www.deviantart.com/nemeionadmin/art/Satchel-893648172", weight: 35 },
        { name: "Scroll in a Bottle", image: "images/BottleScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Scroll-in-a-Bottle-1048423442", weight: 2 },
        { name: "Shank Bone Treat", image: "images/ShankTreat.png", link: "https://www.deviantart.com/nemeionadmin/art/Shank-Bone-Treat-893648243", weight: 7 },
        { name: "Shield", image: "images/Shield.png", link: "https://www.deviantart.com/nemeionadmin/art/Shield-893648529", weight: 35 },
        { name: "Silver Ingot", image: "images/SilverIngot.png", link: "https://www.deviantart.com/nemeionadmin/art/Silver-Ingot-893648584", weight: 2 },
        { name: "Snare", image: "images/Snare.png", link: "https://www.deviantart.com/nemeionadmin/art/Snare-869944565", weight: 35 },
        { name: "Star Ruby", image: "images/StarRuby.png", link: "https://www.deviantart.com/nemeionadmin/art/Star-Ruby-869944706", weight: 3 },
        { name: "Stone Idol", image: "images/StoneIdol.png", link: "https://www.deviantart.com/nemeionadmin/art/Stone-Idol-862974823", weight: 5 },
        { name: "Tiger's Eye", image: "images/TigersEye.png", link: "https://www.deviantart.com/nemeionadmin/art/Tiger-s-Eye-869944883", weight: 3 },
        { name: "Tincture of Transformation", image: "images/Tincture.png", link: "https://www.deviantart.com/nemeionadmin/art/Tincture-of-Transformation-937796429", weight: 2 },
        { name: "Topaz", image: "images/Topaz.png", link: "https://www.deviantart.com/nemeionadmin/art/Topaz-990295373", weight: 2 },
        { name: "Torch", image: "images/Torch.png", link: "https://www.deviantart.com/nemeionadmin/art/Torch-869945140", weight: 35 },
        { name: "Trait Tome", image: "images/TraitTome.png", link: "https://www.deviantart.com/nemeionadmin/art/Trait-Tome-1149003056", weight: 3 },
        { name: "Trap Netting", image: "images/TrapNetting.png", link: "https://www.deviantart.com/nemeionadmin/art/Trap-Netting-869945444", weight: 35 },
        { name: "Uncommon Scroll", image: "images/UScroll.png", link: "https://www.deviantart.com/nemeionadmin/art/Uncommon-Scroll-893785302", weight: 4 },
        { name: "Unicorn Meat", image: "images/UnicornMeat.png", link: "https://www.deviantart.com/nemeionadmin/art/Unicorn-Meat-1037691492", weight: 2 },
        { name: "Upgrade Kit II", image: "images/Kit1.png", link: "https://www.deviantart.com/nemeionadmin/art/Upgrade-Kit-Tier-II-821022538", weight: 5 },
        { name: "Upgrade Kit III", image: "images/Kit2.png", link: "https://www.deviantart.com/nemeionadmin/art/Upgrade-Kit-Tier-III-821022605", weight: 3 },
        { name: "Upgrade Kit IV", image: "images/Kit3.png", link: "https://www.deviantart.com/nemeionadmin/art/Upgrade-Kit-Tier-IV-821022672", weight: 2 },
        { name: "Warpaints", image: "images/Warpaints.png", link: "https://www.deviantart.com/nemeionadmin/art/Warpaints-893785368", weight: 60 },
        { name: "Wax", image: "images/Wax.png", link: "https://www.deviantart.com/nemeionadmin/art/Wax-869945413", weight: 70 },
        { name: "Wicker Basket", image: "images/WickerBasket.png", link: "https://www.deviantart.com/nemeionadmin/art/Wicker-Basket-1149028186", weight: 35 },
        { name: "Wire", image: "images/Wire.png", link: "https://www.deviantart.com/nemeionadmin/art/Wire-869945702", weight: 50 },
        { name: "Wishing Lamp", image: "images/Lamp.png", link: "https://www.deviantart.com/nemeionadmin/art/Wishing-Lamp-1000416215", weight: 1 }
    ],
    trunk: [
        { name: "Pickaxe", image: "images/Pickaxe.png", link: "https://www.deviantart.com/nemeionadmin/art/Pickaxe-893647118", weight: 5 },
        { name: "Alcohol", image: "images/Alcohol.png", link: "https://www.deviantart.com/nemeionadmin/art/Alcohol-937794821", weight: 9 },
        { name: "Pouch of Herbs", image: "images/HerbPouch.png", link: "https://www.deviantart.com/nemeionadmin/art/Pouch-of-Herbs-893647196", weight: 3 },
        { name: "Small White Pelt", image: "images/SmallWhite.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-White-Pelt-893784323", weight: 7 },
        { name: "Small Cream Pelt", image: "images/SmallCream.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Cream-Pelt-893784276", weight: 7 },
        { name: "Thread", image: "images/Thread.png", link: "https://www.deviantart.com/nemeionadmin/art/Thread-893785187", weight: 7 },
        { name: "Ginger", image: "images/Ginger.png", link: "https://www.deviantart.com/nemeionadmin/art/Ginger-893643921", weight: 5 },
        { name: "Bandages", image: "images/Bandages.png", link: "https://www.deviantart.com/nemeionadmin/art/Bandages-893640088", weight: 7 },
        { name: "Glass Bottle", image: "images/GlassBottle.png", link: "https://www.deviantart.com/nemeionadmin/art/Glass-Bottle-862974216", weight: 7 },
        { name: "Glass Jar", image: "images/GlassJar.png", link: "https://www.deviantart.com/nemeionadmin/art/Glass-Jar-893644028", weight: 7 },
        { name: "Jar of Milk", image: "images/MilkJar.png", link: "https://www.deviantart.com/nemeionadmin/art/Jar-of-Milk-990300873", weight: 4 },
        { name: "Jar of Water", image: "images/WaterJar.png", link: "https://www.deviantart.com/nemeionadmin/art/Jar-of-Water-1000416772", weight: 4 },
        { name: "Small Tan Pelt", image: "images/SmallTan.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Tan-Pelt-893784302", weight: 7 },
        { name: "Small Brown Pelt", image: "images/SmallBrown.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Brown-Pelt-893784263", weight: 7 },
        { name: "Small Black Pelt", image: "images/SmallBlack.png", link: "https://www.deviantart.com/nemeionadmin/art/Small-Black-Pelt-893784191", weight: 7 }
    ],
};

